jQuery.fancybox.defaults.i18n = {
	cs: {
		CLOSE: "Zavřít",
		NEXT: "Další",
		PREV: "Předchozí",
		ERROR: "",
		PLAY_START: "Spustit prezentaci",
		PLAY_STOP: "Pozastavit prezentaci",
		FULL_SCREEN: "Celá obrazovka",
		THUMBS: "Náhledy",
		DOWNLOAD: "Stáhnout",
		ZOOM: "Přiblížit"
	},
	de: {
		CLOSE: "Schliessen",
		NEXT: "Weiter",
		PREV: "Zurück",
		ERROR: "Die angeforderten Daten konnten nicht geladen werden.<br/>Bitte versuchen Sie es später nochmal.",
		PLAY_START: "Diaschau starten",
		PLAY_STOP: "Diaschau beenden",
		FULL_SCREEN: "Vollbild",
		THUMBS: "Vorschaubilder",
		DOWNLOAD: "Herunterladen",
		ZOOM: "Maßstab"
	},
	en: {
		CLOSE: "Close",
		NEXT: "Next",
		PREV: "Previous",
		ERROR: "The requested content cannot be loaded.<br/>Please try again later.",
		PLAY_START: "Start slideshow",
		PLAY_STOP: "Pause slideshow",
		FULL_SCREEN: "Full screen",
		THUMBS: "Thumbnails",
		DOWNLOAD: "Download",
		ZOOM: "Zoom"
	},
	es: {
		CLOSE: "Cerrar",
		NEXT: "Siguiente",
		PREV: "Anterior",
		ERROR: "No se puede cargar el contenido solicitado.<br/>Por favor intente de nuevo.",
		PLAY_START: "Inicias diapositivas",
		PLAY_STOP: "Pausar diapositivas",
		FULL_SCREEN: "Pantalla completa",
		THUMBS: "Miniaturas",
		DOWNLOAD: "Descargar",
		ZOOM: "Zoom"
	},
	fr: {
		CLOSE: "Fermer",
		NEXT: "Suivante",
		PREV: "Précédente",
		ERROR: "Le contenu demandé ne peut être chargé.<br />Veuillez réessayer plus tard.",
		PLAY_START: "Démarrer",
		PLAY_STOP: "Pause",
		FULL_SCREEN: "Plein écran",
		THUMBS: "Vignettes",
		DOWNLOAD: "Télécharger",
		ZOOM: "Zoom"
	},
	hu: {
		CLOSE: "Bezárás",
		NEXT: "Következő",
		PREV: "Előző",
		ERROR: "A kért tartalom nem elérhető.<br/>Kérem próbálja újra később.",
		PLAY_START: "Diavetítés indítása",
		PLAY_STOP: "Diavetítés megállítása",
		FULL_SCREEN: "Teljes képernyő",
		THUMBS: "Bélyegképek",
		DOWNLOAD: "Kép letöltése",
		ZOOM: "Nagyítás"
	},
	nl: {
		CLOSE: "Sluiten",
		NEXT: "Volgende",
		PREV: "Vorige",
		ERROR: "De gevraagde inhoud kan niet worden geladen.<br/>Probeer het later nog een keer.",
		PLAY_START: "Start diashow",
		PLAY_STOP: "Pauzeer diashow",
		FULL_SCREEN: "Volledig scherm",
		THUMBS: "Miniaturen",
		DOWNLOAD: "Downloaden",
		ZOOM: "Zomen"
	},
	pl: {
		CLOSE: "Zamknij",
		NEXT: "Następny",
		PREV: "Poprzedni",
		ERROR: "Wystąpił błąd podczas ładowania zawartości.<br>Spróbuj ponownie.",
		PLAY_START: "Włącz automatyczne przeglądanie",
		PLAY_STOP: "Zatrzymaj automatyczne przeglądanie",
		FULL_SCREEN: "Pełny ekran",
		THUMBS: "Miniatury",
		DOWNLOAD: "Pobierz",
		ZOOM: "Przybliż"
	},
	ru: {
		CLOSE: "Закрыть",
		NEXT: "Назад",
		PREV: "Вперёд",
		ERROR: "Не удалось установить соединение.<br/>Пожалуйста, попробуйте позднее.",
		PLAY_START: "Начать слайдшоу",
		PLAY_STOP: "Поставить на паузу",
		FULL_SCREEN: "На полный экран",
		THUMBS: "Превьюшки",
		DOWNLOAD: "Загрузить",
		ZOOM: "Увеличить"
	}
};
